## 1.What is a neural network? What are the general steps required to build a neural network? 

Neural network represents the structure of a human brain modeled on the computer. 
It consists of neurons and synapses organized into layers.

ANN can have millions of neurons connected into one system, which makes it extremely successful at analyzing and 
even memorizing various information.

Neural networks are used to solve complex problems that require analytical calculations similar to those of the human brain. 
The most common uses for neural networks are:Classification,prediction and recognition.
    
Steps required to build a neural network:

    1) Import the data

    2) Split into train and test 
    
    3) Standardize our dataset
    
    4) Define Network
    
    5) Compile Network
    
    6) Evaluate Network
    
    7)Make Predictions
  

## 2.Generally, how do you check the performance of a neural network? Why?

There are different metrics for chrecking the performance of neural network 
Regression metrics :

    Mean squared error 
    
    Mean absolute error
    
    Mean absolute percentage error 
    
    Cosine proximity 
    
Classification Metrics :

    Binary accuracy

    categorical accuracy

    sparse categorical accuracy 


## 3.	Create a neural network using keras to predict the outcome of either of these datasets

WE are taking Abalone dataset for this problem

In [377]:
import pandas as pd
abalone_df = pd.read_csv("Abalone data.csv", sep=",",header=None)
abalone_df.columns=['sex','length','diameter','height','whole_wt','shucked_wt','viscera_wt','shell_wt','rings']
abalone_df

sex  length  diameter  height  whole_wt  shucked_wt  viscera_wt  \
0      M   0.455     0.365   0.095    0.5140      0.2245      0.1010   
1      M   0.350     0.265   0.090    0.2255      0.0995      0.0485   
2      F   0.530     0.420   0.135    0.6770      0.2565      0.1415   
3      M   0.440     0.365   0.125    0.5160      0.2155      0.1140   
4      I   0.330     0.255   0.080    0.2050      0.0895      0.0395   
...   ..     ...       ...     ...       ...         ...         ...   
4172   F   0.565     0.450   0.165    0.8870      0.3700      0.2390   
4173   M   0.590     0.440   0.135    0.9660      0.4390      0.2145   
4174   M   0.600     0.475   0.205    1.1760      0.5255      0.2875   
4175   F   0.625     0.485   0.150    1.0945      0.5310      0.2610   
4176   M   0.710     0.555   0.195    1.9485      0.9455      0.3765   

      shell_wt  rings  
0       0.1500     15  
1       0.0700      7  
2       0.2100      9  
3       0.1550     10  
4       0.0550      7  
...        ...    ...  
4172    0.2490     11  
4173    0.2605     10  
4174    0.3080      9  
4175    0.2960     10  
4176    0.4950     12  

[4177 rows x 9 columns]

In [378]:
# Preprocessing
#Adding a column which converts number of rings to years by adding 1.5 as indicated in the documentation. 
#I do this now since the ultimate desired outcome for this assignment is to predict age.

#Calculating the age using a lambda function
abalone_df['age'] = abalone_df.apply(lambda row : row['rings'] + 1.5, axis = 1)

#viewing the dataframe to confirm column was added correctly and that math looks correct
abalone_df.head()

sex  length  diameter  height  whole_wt  shucked_wt  viscera_wt  shell_wt  \
0   M   0.455     0.365   0.095    0.5140      0.2245      0.1010     0.150   
1   M   0.350     0.265   0.090    0.2255      0.0995      0.0485     0.070   
2   F   0.530     0.420   0.135    0.6770      0.2565      0.1415     0.210   
3   M   0.440     0.365   0.125    0.5160      0.2155      0.1140     0.155   
4   I   0.330     0.255   0.080    0.2050      0.0895      0.0395     0.055   

   rings   age  
0     15  16.5  
1      7   8.5  
2      9  10.5  
3     10  11.5  
4      7   8.5

Checking for missing values


In [379]:
abalone_df.isna().sum()

sex           0
length        0
diameter      0
height        0
whole_wt      0
shucked_wt    0
viscera_wt    0
shell_wt      0
rings         0
age           0
dtype: int64

In [380]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
abalone_df['sex_cat'] = labelencoder.fit_transform(abalone_df['sex'])

In [381]:
abalone_df

sex  length  diameter  height  whole_wt  shucked_wt  viscera_wt  \
0      M   0.455     0.365   0.095    0.5140      0.2245      0.1010   
1      M   0.350     0.265   0.090    0.2255      0.0995      0.0485   
2      F   0.530     0.420   0.135    0.6770      0.2565      0.1415   
3      M   0.440     0.365   0.125    0.5160      0.2155      0.1140   
4      I   0.330     0.255   0.080    0.2050      0.0895      0.0395   
...   ..     ...       ...     ...       ...         ...         ...   
4172   F   0.565     0.450   0.165    0.8870      0.3700      0.2390   
4173   M   0.590     0.440   0.135    0.9660      0.4390      0.2145   
4174   M   0.600     0.475   0.205    1.1760      0.5255      0.2875   
4175   F   0.625     0.485   0.150    1.0945      0.5310      0.2610   
4176   M   0.710     0.555   0.195    1.9485      0.9455      0.3765   

      shell_wt  rings   age  sex_cat  
0       0.1500     15  16.5        2  
1       0.0700      7   8.5        2  
2       0.2100      9  10.5        0  
3       0.1550     10  11.5        2  
4       0.0550      7   8.5        1  
...        ...    ...   ...      ...  
4172    0.2490     11  12.5        0  
4173    0.2605     10  11.5        2  
4174    0.3080      9  10.5        2  
4175    0.2960     10  11.5        0  
4176    0.4950     12  13.5        2  

[4177 rows x 11 columns]

In [382]:
#Removing outliers using z-score
#Some columns are observed to have outliers


from scipy import stats
# must drop sex from zscore since that is string object
z = np.abs(stats.zscore(abalone_df.drop('sex', axis=1)))
print(len(z))
print(z)

4177
[[0.57455813 0.43214879 1.06442415 ... 1.57154357 1.57154357 1.15198011]
 [1.44898585 1.439929   1.18397831 ... 0.91001299 0.91001299 1.15198011]
 [0.05003309 0.12213032 0.10799087 ... 0.28962385 0.28962385 1.28068972]
 ...
 [0.6329849  0.67640943 1.56576738 ... 0.28962385 0.28962385 1.15198011]
 [0.84118198 0.77718745 0.25067161 ... 0.02057072 0.02057072 1.28068972]
 [1.54905203 1.48263359 1.32665906 ... 0.64095986 0.64095986 1.15198011]]


In [383]:
#The first array contains the list of row numbers and second
#array respective column numbers, which mean z[27][13] have a Z-score higher than 3.

threshold = 3
print(np.where(z > 3))
print(z[6][7])

(array([   6,    6,   72,   72,   81,   83,   83,  129,  163,  164,  165,
        165,  165,  166,  166,  166,  167,  167,  168,  170,  181,  181,
        232,  232,  236,  236,  236,  237,  237,  238,  238,  239,  270,
        270,  275,  275,  277,  278,  278,  294,  294,  310,  310,  313,
        313,  314,  314,  334,  351,  351,  355,  355,  358,  358,  362,
        362,  375,  375,  416,  416,  417,  417,  428,  428,  431,  431,
        433,  433,  469,  469,  478,  478,  480,  480,  501,  501,  526,
        526,  530,  530,  572,  572,  628,  628,  673,  673,  674,  674,
        675,  675,  678,  678,  694,  696,  696,  719,  719,  720,  720,
        744,  744,  754,  754,  756,  756,  811,  811,  891,  891,  891,
       1048, 1051, 1051, 1052, 1193, 1197, 1199, 1202, 1204, 1206, 1206,
       1207, 1207, 1207, 1207, 1209, 1209, 1257, 1417, 1417, 1418, 1422,
       1426, 1427, 1427, 1427, 1428, 1429, 1429, 1528, 1754, 1756, 1757,
       1759, 1761, 1762, 1762, 1762, 1763, 1763, 1

In [384]:
abalone_df = abalone_df[(z < 3).all(axis=1)]

In [385]:
abalone_df

sex  length  diameter  height  whole_wt  shucked_wt  viscera_wt  \
0      M   0.455     0.365   0.095    0.5140      0.2245      0.1010   
1      M   0.350     0.265   0.090    0.2255      0.0995      0.0485   
2      F   0.530     0.420   0.135    0.6770      0.2565      0.1415   
3      M   0.440     0.365   0.125    0.5160      0.2155      0.1140   
4      I   0.330     0.255   0.080    0.2050      0.0895      0.0395   
...   ..     ...       ...     ...       ...         ...         ...   
4172   F   0.565     0.450   0.165    0.8870      0.3700      0.2390   
4173   M   0.590     0.440   0.135    0.9660      0.4390      0.2145   
4174   M   0.600     0.475   0.205    1.1760      0.5255      0.2875   
4175   F   0.625     0.485   0.150    1.0945      0.5310      0.2610   
4176   M   0.710     0.555   0.195    1.9485      0.9455      0.3765   

      shell_wt  rings   age  sex_cat  
0       0.1500     15  16.5        2  
1       0.0700      7   8.5        2  
2       0.2100      9  10.5        0  
3       0.1550     10  11.5        2  
4       0.0550      7   8.5        1  
...        ...    ...   ...      ...  
4172    0.2490     11  12.5        0  
4173    0.2605     10  11.5        2  
4174    0.3080      9  10.5        2  
4175    0.2960     10  11.5        0  
4176    0.4950     12  13.5        2  

[4027 rows x 11 columns]

In [387]:
abalone_df.columns

Index(['sex', 'length', 'diameter', 'height', 'whole_wt', 'shucked_wt',
       'viscera_wt', 'shell_wt', 'rings', 'age', 'sex_cat'],
      dtype='object')

In [388]:
#Checking correlation 
abalone_df.corr()

length  diameter    height  whole_wt  shucked_wt  viscera_wt  \
length      1.000000  0.986011  0.895432  0.934410    0.909245    0.907957   
diameter    0.986011  1.000000  0.901803  0.934069    0.904302    0.904192   
height      0.895432  0.901803  1.000000  0.891783    0.843010    0.869273   
whole_wt    0.934410  0.934069  0.891783  1.000000    0.971024    0.966612   
shucked_wt  0.909245  0.904302  0.843010  0.971024    1.000000    0.930154   
viscera_wt  0.907957  0.904192  0.869273  0.966612    0.930154    1.000000   
shell_wt    0.914518  0.921779  0.899716  0.961216    0.896220    0.919414   
rings       0.567074  0.584978  0.612540  0.548295    0.440424    0.522917   
age         0.567074  0.584978  0.612540  0.548295    0.440424    0.522917   
sex_cat    -0.043639 -0.046531 -0.046282 -0.034776   -0.016457   -0.045292   

            shell_wt     rings       age   sex_cat  
length      0.914518  0.567074  0.567074 -0.043639  
diameter    0.921779  0.584978  0.584978 -0.046531  
height      0.899716  0.612540  0.612540 -0.046282  
whole_wt    0.961216  0.548295  0.548295 -0.034776  
shucked_wt  0.896220  0.440424  0.440424 -0.016457  
viscera_wt  0.919414  0.522917  0.522917 -0.045292  
shell_wt    1.000000  0.622872  0.622872 -0.043825  
rings       0.622872  1.000000  1.000000 -0.033272  
age         0.622872  1.000000  1.000000 -0.033272  
sex_cat    -0.043825 -0.033272 -0.033272  1.000000

In [389]:
abalone_df

sex  length  diameter  height  whole_wt  shucked_wt  viscera_wt  \
0      M   0.455     0.365   0.095    0.5140      0.2245      0.1010   
1      M   0.350     0.265   0.090    0.2255      0.0995      0.0485   
2      F   0.530     0.420   0.135    0.6770      0.2565      0.1415   
3      M   0.440     0.365   0.125    0.5160      0.2155      0.1140   
4      I   0.330     0.255   0.080    0.2050      0.0895      0.0395   
...   ..     ...       ...     ...       ...         ...         ...   
4172   F   0.565     0.450   0.165    0.8870      0.3700      0.2390   
4173   M   0.590     0.440   0.135    0.9660      0.4390      0.2145   
4174   M   0.600     0.475   0.205    1.1760      0.5255      0.2875   
4175   F   0.625     0.485   0.150    1.0945      0.5310      0.2610   
4176   M   0.710     0.555   0.195    1.9485      0.9455      0.3765   

      shell_wt  rings   age  sex_cat  
0       0.1500     15  16.5        2  
1       0.0700      7   8.5        2  
2       0.2100      9  10.5        0  
3       0.1550     10  11.5        2  
4       0.0550      7   8.5        1  
...        ...    ...   ...      ...  
4172    0.2490     11  12.5        0  
4173    0.2605     10  11.5        2  
4174    0.3080      9  10.5        2  
4175    0.2960     10  11.5        0  
4176    0.4950     12  13.5        2  

[4027 rows x 11 columns]

In [392]:
#Binning the data
#The bins will be for rings : (0,3],(3, 9]  (9, 11], and (11, 19]where The left bin edge will be exclusive 
#and the right bin edge will be inclusive.

bins = [0,3,9,11,19]
label  = [0,1,2,3]
abalone_df['rings_bin'] = pd.cut(abalone_df['rings'],bins,labels=label)


<ipython-input-392-42e15a9dd795>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abalone_df['rings_bin'] = pd.cut(abalone_df['rings'],bins,labels=label)


In [406]:
#Dropping unnecessary columns
columns = ['age','sex']
abalone_df.drop(columns,axis=1,inplace=True)

c:\users\sunny\appdata\local\programs\python\python38\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [410]:
#Checking the shape
abalone_df.shape

(4027, 10)

In [412]:
abalone_df.columns

Index(['length', 'diameter', 'height', 'whole_wt', 'shucked_wt', 'viscera_wt',
       'shell_wt', 'rings', 'sex_cat', 'rings_bin'],
      dtype='object')

## Solving it as a Classification problem

In [427]:
X = abalone_df[['length','diameter','height','whole_wt','shucked_wt','viscera_wt','shell_wt','sex_cat']]
y = abalone_df['rings_bin']

# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42, stratify=y)


# #Standardize
sc= StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)


from keras.models import Sequential
from keras.layers import Dense

#Defining model
model = Sequential()
model.add(Dense(4, input_dim=8, activation='relu'))
model.add(Dense(4, activation='relu'))
#model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='softmax'))
          
#Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) 
                             
model.fit(X_train, y_train,epochs=100, batch_size=10, verbose=1)

pred_train= model.predict(X_train)

scores = model.evaluate(X_train, y_train, verbose=0)
print('Accuracy on training data: {}% \n Error on training data: {}'.format(scores[1], 1 - scores[1]))   
 
pred_test= model.predict(X_test)
scores2 = model.evaluate(X_test, y_test, verbose=0)
print('Accuracy on test data: {}% \n Error on test data: {}'.format(scores2[1], 1 - scores2[1])) 


Epoch 1/100
282/282 [==============================] - 1s 737us/step - loss: 0.0000e+00 - accuracy: 0.5076
Epoch 2/100
282/282 [==============================] - 0s 741us/step - loss: 0.0000e+00 - accuracy: 0.5246
Epoch 3/100
282/282 [==============================] - 0s 801us/step - loss: 0.0000e+00 - accuracy: 0.5056
Epoch 4/100
282/282 [==============================] - 0s 762us/step - loss: 0.0000e+00 - accuracy: 0.5094
Epoch 5/100
282/282 [==============================] - 0s 765us/step - loss: 0.0000e+00 - accuracy: 0.5146
Epoch 6/100
282/282 [==============================] - 0s 788us/step - loss: 0.0000e+00 - accuracy: 0.5181
Epoch 7/100
282/282 [==============================] - 0s 800us/step - loss: 0.0000e+00 - accuracy: 0.5018
Epoch 8/100
282/282 [==============================] - 0s 764us/step - loss: 0.0000e+00 - accuracy: 0.5116
Epoch 9/100
282/282 [==============================] - 0s 791us/step - loss: 0.0000e+00 - accuracy: 0.5169
Epoch 10/100
282/282 [===============

Epoch 77/100
282/282 [==============================] - 0s 786us/step - loss: 0.0000e+00 - accuracy: 0.5109
Epoch 78/100
282/282 [==============================] - 0s 742us/step - loss: 0.0000e+00 - accuracy: 0.5205
Epoch 79/100
282/282 [==============================] - 0s 816us/step - loss: 0.0000e+00 - accuracy: 0.5045
Epoch 80/100
282/282 [==============================] - 0s 768us/step - loss: 0.0000e+00 - accuracy: 0.5122
Epoch 81/100
282/282 [==============================] - 0s 778us/step - loss: 0.0000e+00 - accuracy: 0.5192
Epoch 82/100
282/282 [==============================] - 0s 749us/step - loss: 0.0000e+00 - accuracy: 0.5086
Epoch 83/100
282/282 [==============================] - 0s 751us/step - loss: 0.0000e+00 - accuracy: 0.5029
Epoch 84/100
282/282 [==============================] - 0s 768us/step - loss: 0.0000e+00 - accuracy: 0.5198
Epoch 85/100
282/282 [==============================] - 0s 804us/step - loss: 0.0000e+00 - accuracy: 0.5144
Epoch 86/100
282/282 [======

## Solving  as a Regression problem 

In [431]:
X = abalone_df[['length','diameter','height','whole_wt','shucked_wt','viscera_wt','shell_wt','sex_cat']]
y = abalone_df['rings']

# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42, stratify=y)


# #Standardize
sc= StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import RMSprop
model = Sequential()
model.add(Dense(units=10, input_dim=8,activation='relu'))
model.add(Dense(units=1,activation='linear'))
model.compile(optimizer='adam', loss='mean_squared_error',  metrics=['mae','mse'])

#early_stop = keras.callbacks.EarlyStopping(monitor='val_loss', patience=10)
model.fit(X_train,y_train,batch_size=5,epochs=1000)
# Model summary for number of parameters use in the algorithm
model.summary()


Epoch 1/1000
564/564 [==============================] - 1s 750us/step - loss: 75.0177 - mae: 8.0342 - mse: 75.0177
Epoch 2/1000
564/564 [==============================] - 0s 751us/step - loss: 21.1246 - mae: 3.7073 - mse: 21.1246
Epoch 3/1000
564/564 [==============================] - 0s 733us/step - loss: 8.8205 - mae: 2.2657 - mse: 8.8205
Epoch 4/1000
564/564 [==============================] - 0s 731us/step - loss: 5.5717 - mae: 1.7316 - mse: 5.5717
Epoch 5/1000
564/564 [==============================] - 0s 753us/step - loss: 4.7513 - mae: 1.6018 - mse: 4.7513
Epoch 6/1000
564/564 [==============================] - 0s 750us/step - loss: 4.3415 - mae: 1.5437 - mse: 4.3415
Epoch 7/1000
564/564 [==============================] - 0s 785us/step - loss: 4.3655 - mae: 1.5514 - mse: 4.3655
Epoch 8/1000
564/564 [==============================] - 0s 772us/step - loss: 3.9630 - mae: 1.4676 - mse: 3.9630
Epoch 9/1000
564/564 [==============================] - 1s 903us/step - loss: 4.1509 - mae: 

564/564 [==============================] - 1s 915us/step - loss: 3.4444 - mae: 1.3772 - mse: 3.4444
Epoch 74/1000
564/564 [==============================] - 1s 1ms/step - loss: 3.3671 - mae: 1.3584 - mse: 3.3671
Epoch 75/1000
564/564 [==============================] - 1s 944us/step - loss: 3.3060 - mae: 1.3365 - mse: 3.3060
Epoch 76/1000
564/564 [==============================] - 0s 876us/step - loss: 3.4218 - mae: 1.3871 - mse: 3.4218
Epoch 77/1000
564/564 [==============================] - 0s 838us/step - loss: 3.3827 - mae: 1.3463 - mse: 3.3827
Epoch 78/1000
564/564 [==============================] - 0s 867us/step - loss: 3.5619 - mae: 1.3882 - mse: 3.5619
Epoch 79/1000
564/564 [==============================] - 1s 920us/step - loss: 3.6112 - mae: 1.3991 - mse: 3.6112
Epoch 80/1000
564/564 [==============================] - 1s 919us/step - loss: 3.4204 - mae: 1.3566 - mse: 3.4204
Epoch 81/1000
564/564 [==============================] - 1s 906us/step - loss: 3.5217 - mae: 1.3772 - ms

564/564 [==============================] - 1s 918us/step - loss: 3.3962 - mae: 1.3619 - mse: 3.3962
Epoch 145/1000
564/564 [==============================] - 1s 957us/step - loss: 3.2505 - mae: 1.3498 - mse: 3.2505
Epoch 146/1000
564/564 [==============================] - 1s 886us/step - loss: 3.3815 - mae: 1.3616 - mse: 3.3815
Epoch 147/1000
564/564 [==============================] - 1s 907us/step - loss: 3.3667 - mae: 1.3623 - mse: 3.3667
Epoch 148/1000
564/564 [==============================] - 1s 903us/step - loss: 3.3038 - mae: 1.3470 - mse: 3.3038
Epoch 149/1000
564/564 [==============================] - 1s 934us/step - loss: 3.5242 - mae: 1.3801 - mse: 3.5242
Epoch 150/1000
564/564 [==============================] - 1s 914us/step - loss: 3.3162 - mae: 1.3558 - mse: 3.3162
Epoch 151/1000
564/564 [==============================] - 1s 913us/step - loss: 3.4867 - mae: 1.3735 - mse: 3.4867
Epoch 152/1000
564/564 [==============================] - 1s 903us/step - loss: 3.3053 - mae: 1

564/564 [==============================] - 1s 893us/step - loss: 3.2629 - mae: 1.3292 - mse: 3.2629
Epoch 216/1000
564/564 [==============================] - 1s 916us/step - loss: 3.4065 - mae: 1.3695 - mse: 3.4065
Epoch 217/1000
564/564 [==============================] - 1s 974us/step - loss: 3.3518 - mae: 1.3488 - mse: 3.3518
Epoch 218/1000
564/564 [==============================] - 1s 1ms/step - loss: 3.2054 - mae: 1.3178 - mse: 3.2054
Epoch 219/1000
564/564 [==============================] - 1s 925us/step - loss: 3.4894 - mae: 1.3601 - mse: 3.4894
Epoch 220/1000
564/564 [==============================] - 0s 872us/step - loss: 3.3713 - mae: 1.3565 - mse: 3.3713
Epoch 221/1000
564/564 [==============================] - 1s 956us/step - loss: 3.3041 - mae: 1.3600 - mse: 3.3041
Epoch 222/1000
564/564 [==============================] - 1s 1ms/step - loss: 3.4291 - mae: 1.3616 - mse: 3.4291
Epoch 223/1000
564/564 [==============================] - 1s 940us/step - loss: 3.1677 - mae: 1.318

564/564 [==============================] - 1s 930us/step - loss: 3.2983 - mae: 1.3540 - mse: 3.2983
Epoch 287/1000
564/564 [==============================] - 1s 928us/step - loss: 3.1594 - mae: 1.3232 - mse: 3.1594
Epoch 288/1000
564/564 [==============================] - 0s 869us/step - loss: 3.1836 - mae: 1.3292 - mse: 3.1836
Epoch 289/1000
564/564 [==============================] - 1s 890us/step - loss: 3.5863 - mae: 1.3749 - mse: 3.5863
Epoch 290/1000
564/564 [==============================] - 1s 909us/step - loss: 3.4802 - mae: 1.3677 - mse: 3.4802
Epoch 291/1000
564/564 [==============================] - 1s 890us/step - loss: 3.3234 - mae: 1.3379 - mse: 3.3234
Epoch 292/1000
564/564 [==============================] - 1s 914us/step - loss: 3.0601 - mae: 1.2864 - mse: 3.0601
Epoch 293/1000
564/564 [==============================] - 1s 931us/step - loss: 3.3162 - mae: 1.3426 - mse: 3.3162
Epoch 294/1000
564/564 [==============================] - 1s 947us/step - loss: 3.1916 - mae: 1

564/564 [==============================] - 1s 955us/step - loss: 3.2669 - mae: 1.3289 - mse: 3.2669
Epoch 358/1000
564/564 [==============================] - 0s 883us/step - loss: 3.2019 - mae: 1.3088 - mse: 3.2019
Epoch 359/1000
564/564 [==============================] - 0s 861us/step - loss: 3.4471 - mae: 1.3728 - mse: 3.4471
Epoch 360/1000
564/564 [==============================] - 0s 880us/step - loss: 3.5733 - mae: 1.3852 - mse: 3.5733
Epoch 361/1000
564/564 [==============================] - 1s 975us/step - loss: 3.4302 - mae: 1.3558 - mse: 3.4302
Epoch 362/1000
564/564 [==============================] - 0s 868us/step - loss: 3.4029 - mae: 1.3552 - mse: 3.4029
Epoch 363/1000
564/564 [==============================] - 0s 872us/step - loss: 3.1214 - mae: 1.3080 - mse: 3.1214
Epoch 364/1000
564/564 [==============================] - 1s 900us/step - loss: 3.5399 - mae: 1.3996 - mse: 3.5399
Epoch 365/1000
564/564 [==============================] - 0s 867us/step - loss: 3.4089 - mae: 1

564/564 [==============================] - 1s 898us/step - loss: 3.6967 - mae: 1.4100 - mse: 3.6967
Epoch 429/1000
564/564 [==============================] - 1s 931us/step - loss: 3.1321 - mae: 1.3023 - mse: 3.1321
Epoch 430/1000
564/564 [==============================] - 1s 891us/step - loss: 3.2572 - mae: 1.3318 - mse: 3.2572
Epoch 431/1000
564/564 [==============================] - 0s 872us/step - loss: 3.3589 - mae: 1.3260 - mse: 3.3589
Epoch 432/1000
564/564 [==============================] - 0s 852us/step - loss: 3.4793 - mae: 1.3754 - mse: 3.4793
Epoch 433/1000
564/564 [==============================] - 1s 889us/step - loss: 3.4005 - mae: 1.3527 - mse: 3.4005
Epoch 434/1000
564/564 [==============================] - 0s 886us/step - loss: 3.1460 - mae: 1.3197 - mse: 3.1460
Epoch 435/1000
564/564 [==============================] - 0s 865us/step - loss: 3.3724 - mae: 1.3636 - mse: 3.3724
Epoch 436/1000
564/564 [==============================] - 0s 880us/step - loss: 3.2656 - mae: 1

564/564 [==============================] - 0s 872us/step - loss: 3.1225 - mae: 1.3207 - mse: 3.1225
Epoch 500/1000
564/564 [==============================] - 1s 891us/step - loss: 3.2964 - mae: 1.3443 - mse: 3.2964
Epoch 501/1000
564/564 [==============================] - 0s 881us/step - loss: 3.2303 - mae: 1.3241 - mse: 3.2303
Epoch 502/1000
564/564 [==============================] - 0s 884us/step - loss: 3.4554 - mae: 1.3646 - mse: 3.4554
Epoch 503/1000
564/564 [==============================] - 0s 847us/step - loss: 3.3663 - mae: 1.3561 - mse: 3.3663
Epoch 504/1000
564/564 [==============================] - 0s 847us/step - loss: 3.2160 - mae: 1.3275 - mse: 3.2160
Epoch 505/1000
564/564 [==============================] - 0s 860us/step - loss: 3.3611 - mae: 1.3423 - mse: 3.3611
Epoch 506/1000
564/564 [==============================] - 1s 889us/step - loss: 3.1541 - mae: 1.3064 - mse: 3.1541
Epoch 507/1000
564/564 [==============================] - 0s 886us/step - loss: 3.3660 - mae: 1

564/564 [==============================] - 1s 907us/step - loss: 3.2330 - mae: 1.3181 - mse: 3.2330
Epoch 571/1000
564/564 [==============================] - 1s 887us/step - loss: 3.2630 - mae: 1.3456 - mse: 3.2630
Epoch 572/1000
564/564 [==============================] - 0s 867us/step - loss: 3.4225 - mae: 1.3533 - mse: 3.4225
Epoch 573/1000
564/564 [==============================] - 0s 882us/step - loss: 3.4801 - mae: 1.3733 - mse: 3.4801
Epoch 574/1000
564/564 [==============================] - 0s 851us/step - loss: 3.2441 - mae: 1.3465 - mse: 3.2441
Epoch 575/1000
564/564 [==============================] - 0s 847us/step - loss: 3.3299 - mae: 1.3392 - mse: 3.3299
Epoch 576/1000
564/564 [==============================] - 0s 852us/step - loss: 3.4995 - mae: 1.3790 - mse: 3.4995
Epoch 577/1000
564/564 [==============================] - 0s 845us/step - loss: 3.2690 - mae: 1.3323 - mse: 3.2690
Epoch 578/1000
564/564 [==============================] - 0s 848us/step - loss: 3.1752 - mae: 1

564/564 [==============================] - 1s 1ms/step - loss: 3.3309 - mae: 1.3520 - mse: 3.3309
Epoch 642/1000
564/564 [==============================] - 1s 1ms/step - loss: 3.3841 - mae: 1.3610 - mse: 3.3841
Epoch 643/1000
564/564 [==============================] - 1s 893us/step - loss: 3.4470 - mae: 1.3815 - mse: 3.4470
Epoch 644/1000
564/564 [==============================] - 1s 937us/step - loss: 3.3126 - mae: 1.3487 - mse: 3.3126
Epoch 645/1000
564/564 [==============================] - 1s 966us/step - loss: 3.2301 - mae: 1.3218 - mse: 3.2301
Epoch 646/1000
564/564 [==============================] - 1s 892us/step - loss: 3.4638 - mae: 1.3630 - mse: 3.4638
Epoch 647/1000
564/564 [==============================] - 1s 928us/step - loss: 3.5865 - mae: 1.3974 - mse: 3.5865
Epoch 648/1000
564/564 [==============================] - 1s 902us/step - loss: 3.2131 - mae: 1.3321 - mse: 3.2131
Epoch 649/1000
564/564 [==============================] - 1s 900us/step - loss: 3.6602 - mae: 1.395

564/564 [==============================] - 1s 954us/step - loss: 3.4147 - mae: 1.3500 - mse: 3.4147
Epoch 713/1000
564/564 [==============================] - 1s 933us/step - loss: 3.3597 - mae: 1.3581 - mse: 3.3597
Epoch 714/1000
564/564 [==============================] - 1s 961us/step - loss: 3.3527 - mae: 1.3438 - mse: 3.3527
Epoch 715/1000
564/564 [==============================] - 1s 913us/step - loss: 3.3178 - mae: 1.3467 - mse: 3.3178
Epoch 716/1000
564/564 [==============================] - 0s 880us/step - loss: 3.5230 - mae: 1.3828 - mse: 3.5230
Epoch 717/1000
564/564 [==============================] - 0s 880us/step - loss: 3.3398 - mae: 1.3642 - mse: 3.3398
Epoch 718/1000
564/564 [==============================] - 1s 1ms/step - loss: 3.2428 - mae: 1.3302 - mse: 3.2428
Epoch 719/1000
564/564 [==============================] - 1s 986us/step - loss: 3.3557 - mae: 1.3327 - mse: 3.3557
Epoch 720/1000
564/564 [==============================] - 1s 904us/step - loss: 3.2236 - mae: 1.3

564/564 [==============================] - 1s 955us/step - loss: 3.1721 - mae: 1.3031 - mse: 3.1721
Epoch 784/1000
564/564 [==============================] - 1s 966us/step - loss: 3.1800 - mae: 1.3206 - mse: 3.1800
Epoch 785/1000
564/564 [==============================] - 1s 891us/step - loss: 3.2788 - mae: 1.3427 - mse: 3.2788
Epoch 786/1000
564/564 [==============================] - 0s 872us/step - loss: 3.2484 - mae: 1.3261 - mse: 3.2484
Epoch 787/1000
564/564 [==============================] - 0s 884us/step - loss: 3.2747 - mae: 1.3438 - mse: 3.2747
Epoch 788/1000
564/564 [==============================] - 1s 960us/step - loss: 3.2927 - mae: 1.3335 - mse: 3.2927
Epoch 789/1000
564/564 [==============================] - 1s 1ms/step - loss: 3.2781 - mae: 1.3493 - mse: 3.2781
Epoch 790/1000
564/564 [==============================] - 1s 1ms/step - loss: 3.4882 - mae: 1.3743 - mse: 3.4882
Epoch 791/1000
564/564 [==============================] - 1s 936us/step - loss: 3.2639 - mae: 1.339

564/564 [==============================] - 1s 922us/step - loss: 3.2676 - mae: 1.3340 - mse: 3.2676
Epoch 855/1000
564/564 [==============================] - 1s 937us/step - loss: 3.4094 - mae: 1.3556 - mse: 3.4094
Epoch 856/1000
564/564 [==============================] - 1s 959us/step - loss: 3.1726 - mae: 1.3216 - mse: 3.1726
Epoch 857/1000
564/564 [==============================] - 1s 933us/step - loss: 3.1801 - mae: 1.3152 - mse: 3.1801
Epoch 858/1000
564/564 [==============================] - 1s 906us/step - loss: 3.1829 - mae: 1.2968 - mse: 3.1829
Epoch 859/1000
564/564 [==============================] - 1s 892us/step - loss: 3.2500 - mae: 1.3250 - mse: 3.2500
Epoch 860/1000
564/564 [==============================] - 1s 897us/step - loss: 3.4733 - mae: 1.3743 - mse: 3.4733
Epoch 861/1000
564/564 [==============================] - 1s 902us/step - loss: 3.5627 - mae: 1.3850 - mse: 3.5627
Epoch 862/1000
564/564 [==============================] - 1s 892us/step - loss: 3.2915 - mae: 1

564/564 [==============================] - 1s 918us/step - loss: 3.2484 - mae: 1.3362 - mse: 3.2484
Epoch 926/1000
564/564 [==============================] - 1s 893us/step - loss: 3.3430 - mae: 1.3692 - mse: 3.3430
Epoch 927/1000
564/564 [==============================] - 0s 867us/step - loss: 3.5495 - mae: 1.3818 - mse: 3.5495
Epoch 928/1000
564/564 [==============================] - 0s 868us/step - loss: 3.1353 - mae: 1.3095 - mse: 3.1353
Epoch 929/1000
564/564 [==============================] - 0s 873us/step - loss: 3.3603 - mae: 1.3571 - mse: 3.3603
Epoch 930/1000
564/564 [==============================] - 0s 880us/step - loss: 3.3184 - mae: 1.3422 - mse: 3.3184
Epoch 931/1000
564/564 [==============================] - 0s 881us/step - loss: 3.5233 - mae: 1.3790 - mse: 3.5233
Epoch 932/1000
564/564 [==============================] - 1s 895us/step - loss: 3.2959 - mae: 1.3468 - mse: 3.2959
Epoch 933/1000
564/564 [==============================] - 1s 901us/step - loss: 3.3622 - mae: 1

564/564 [==============================] - 0s 886us/step - loss: 3.2887 - mae: 1.3432 - mse: 3.2887
Epoch 997/1000
564/564 [==============================] - 0s 863us/step - loss: 3.3611 - mae: 1.3519 - mse: 3.3611
Epoch 998/1000
564/564 [==============================] - 0s 858us/step - loss: 3.3278 - mae: 1.3437 - mse: 3.3278
Epoch 999/1000
564/564 [==============================] - 0s 869us/step - loss: 3.3795 - mae: 1.3677 - mse: 3.3795
Epoch 1000/1000
564/564 [==============================] - 0s 868us/step - loss: 3.3210 - mae: 1.3366 - mse: 3.3210
Model: "sequential_71"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_240 (Dense)            (None, 10)                90        
_________________________________________________________________
dense_241 (Dense)            (None, 1)                 11        
Total params: 101
Trainable params: 101
Non-trainable params: 0
______________________

In [432]:
#Predict testing labels
y_pred= model.predict(X_test)

#Calculate RMSE and R^2
from sklearn.metrics import mean_squared_error
from math import sqrt
rms = sqrt(mean_squared_error(y_test, y_pred))
print(rms)
from sklearn.metrics import r2_score
r_squared=r2_score(y_test,y_pred)
print(r_squared)

1.9631630282273036
0.5286942580272707


By using keras for regression problem  we got r2_score as 0.52 and RMSE as 1.96

## 4. Write another algorithm to predict the same result as the previous question using either KNN or logistic regression

In [433]:
#Using Logistic regression 
X = abalone_df[['length','diameter','height','whole_wt','shucked_wt','viscera_wt','shell_wt','sex_cat']]
y = abalone_df['rings_bin']

# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42, stratify=y)


# #Standardize
sc= StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)


#Import Library for Logistic Regression
from sklearn.linear_model import LogisticRegression

#Initialize the Logistic Regression Classifier
model = LogisticRegression()

#Train the model using Training Dataset
model.fit(X_train,y_train)

# Prediction using test data
y_pred = model.predict(X_test)

#Import Library for Accuracy Score
from sklearn.metrics import accuracy_score


# Calculate Model accuracy by comparing y_test and y_pred
acc_logisreg=accuracy_score(y_pred,y_test)
print('Logistic Regression accuracy : ',acc_logisreg)



Logistic Regression accuracy :  0.684863523573201


c:\users\sunny\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## 5.	Create a neural network using pytorch to predict the same result as question 3. 

## Using pytorch 

In [470]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = abalone_df1[['length','diameter','height','whole_wt','shucked_wt','viscera_wt','shell_wt','sex_cat']].values
y = abalone_df1['rings'].values

# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42, stratify=y)

# #Standardize
sc= StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [471]:
import torch.nn as nn
import torch.nn.functional as F#this has activation functions
import pandas as pd
import torch
# Creating tensors
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

print(X_train)

tensor([[-0.6999, -0.5752, -0.7575,  ..., -0.8448, -0.7873,  1.1606],
        [ 1.6188,  1.4985,  1.6617,  ...,  2.5444,  2.0915,  1.1606],
        [-0.7857, -0.7826, -1.1607,  ..., -1.0714, -0.8418, -0.0655],
        ...,
        [ 0.7171,  0.9800,  0.9897,  ...,  0.5388,  1.1190,  1.1606],
        [ 1.4900,  1.2392,  1.7961,  ...,  2.1828,  1.7220, -1.2915],
        [ 1.1035,  1.2392,  1.2585,  ...,  0.9823,  1.2084,  1.1606]])


In [472]:
class ANN_Model(nn.Module):
    def __init__(self, input_features=8, hidden1=20, hidden2=20, out_features =1):
        super().__init__()
        self.layer_1_connection = nn.Linear(input_features, hidden1)
        self.layer_2_connection = nn.Linear(hidden1, hidden2)
        self.out = nn.Linear(hidden2, out_features)
    
    def forward(self, x):
        #apply activation functions
        x = F.relu(self.layer_1_connection(x))
        x = F.relu(self.layer_2_connection(x))
        x = self.out(x)
        return x

In [473]:
torch.manual_seed(42)

#instantiate the model
model = ANN_Model()

In [474]:
# loss function
loss_function = nn.CrossEntropyLoss()

#optimizer
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)

In [475]:
#loss_function = nn.CrossEntropyLoss()
#optimizer
#optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)
#optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
    

In [476]:
#run model through multiple epochs/iterations
final_loss = []
n_epochs = 100
for epoch in range(n_epochs):
    y_pred = model.forward(X_train)
    loss = loss_function(y_pred, y_train)
    final_loss.append(loss)
    
    if epoch % 10 == 1:
        print(f'Epoch number: {epoch} with loss: {loss.item()}')
    
    optimizer.zero_grad() #zero the gradient before running backwards propagation
    loss.backward() #for backward propagation 
    optimizer.step() #performs one optimization step each epoch

IndexError: Target 9 is out of bounds.

In [335]:
#predictions
y_pred = []

with torch.no_grad():
    for i, data in enumerate(X_test):
        prediction = model(data)
        y_pred.append(prediction.argmax().item())

In [ ]:
from sklearn.metrics import accuracy_score
a_score = accuracy_score(y_test, y_pred)
print(a_score)

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

## 6.Compare the performance of the neural networks to the other model you created. Which performed better? Why do you think that is?